### ISSUE TITLE
Auto scaling target/policy creation failing in il-central-1

### ISSUE THREAD

**Issue by nishsak96** [terraform-aws-modules/terraform-aws-msk-kafka-cluster#14]
## Description

In regions like il-central-1(Tel Aviv, Israel), we have MSK but it does not support autoscaling groups yet. In such cases when we try to create MSK using this module, it breaks with a "Not Authorized to perform this action" exception. 

If your request is for a new feature, please use the `Feature request` template.

- [Yes ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: Latest

- Terraform version: 1.4.6

- Provider version(s): 5.16.2 (Hashicorp/aws)

## Reproduction Code [Required]

 Create AWS MSK in il-central-1 using this terraform module.

## Expected behavior
Should work. (Making autoscaling targets/policies optional will do the job)

## Actual behavior
Breaking.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.3.0 :tada:
