### ISSUE TITLE
Push v2.5 to Terraform registry

### ISSUE THREAD

**Issue by fedeostrit** [terraform-aws-modules/terraform-aws-msk-kafka-cluster#26]
Hi, I wanted to know if there is any roadmap to see the upload of version v2.5 to the terraform registry, is the current version of the registry in terraform v2.3? 
<img width="1448" alt="image" src="https://github.com/terraform-aws-modules/terraform-aws-msk-kafka-cluster/assets/48490228/1f8e6c61-2e31-4e01-909f-c0c9dfbcbd32">

**Comment by fedeostrit** [comment]
@antonbabenko ?

**Comment by antonbabenko** [comment]
Fixed. Thank you for opening this issue!

**Comment by fedeostrit** [comment]
@antonbabenko  Thank you very much for the management and the quick solution

I need to ask you another question regarding Multi-VPC, is it possible to enable it with the module? Is there any config to do that? Or just enabling create_cluster_policy and adding cluster_policy_statements is it already activated automatically?

**Comment by antonbabenko** [comment]
I am not sure. @bryantbiggs do you know?

**Comment by fedeostrit** [comment]
Activating this through the console and then adding the policy through terra works, the problem is that I cannot find a way to enable multi-VPC from the module and I think it is not in the msk_cluster resource to enable this, I understand that you have to enable it first at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster and then you take the value and add it to your module

**Comment by bryantbiggs** [comment]
Its not supported in the provider at this time https://github.com/hashicorp/terraform-provider-aws/issues/34419
