### ISSUE TITLE
Push v2.6 to Terraform registry

### ISSUE THREAD

**Issue by visah** [terraform-aws-modules/terraform-aws-msk-kafka-cluster#29]
Hello,

Would it be possible to get the 2.6 version to the Terraform registry? Currently 2.5 is the latest in there.

![Screenshot from 2024-06-19 09-44-45](https://github.com/terraform-aws-modules/terraform-aws-msk-kafka-cluster/assets/50622048/667a8797-54fd-44f7-8d90-addf1d0ec4f0)

@antonbabenko

**Comment by bryantbiggs** [comment]
cc @antonbabenko

**Comment by antonbabenko** [comment]
Fixed
