### ISSUE TITLE
Allow change in schema data format

### ISSUE THREAD

**Issue by rcfja** [terraform-aws-modules/terraform-aws-msk-kafka-cluster#31]
## Is your request related to a new offering from AWS?

It was added in 2021
https://aws.amazon.com/pt/about-aws/whats-new/2021/06/aws-glue-schema-registry-now-supports-json-schema/

## Is your request related to a problem? Please describe.

I cannot configure schema to "json" data type

## Describe the solution you'd like.

Please allow this value to be configured when needed:
https://github.com/terraform-aws-modules/terraform-aws-msk-kafka-cluster/blob/master/main.tf#L350
(defaulting to AVRO is of course good and should stay)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.7.0 :tada:

**Comment by rcfja** [comment]
Tested and it works. Thank you!
