### ISSUE TITLE
Cannot correctly import MSK configuration 

### ISSUE THREAD

**Issue by ajax-koval-i** [terraform-aws-modules/terraform-aws-msk-kafka-cluster#39]
## Description
In your module, the resources **`aws_msk_configuration`** and **`random_id`** are used.

If the **`aws_msk_configuration resource`** was created manually or by another module and was given a simple name, for example, **example-configuration**, when importing this resource into your module, the **`aws_msk_configuration`** will always be recreated since you use the **`random_id`** resource in the configuration name.

It would be great to have the option to correctly import resources into your public module.

For example, by adding the ability to disable the random-id suffix at the end of the name.

## Versions

- Module version: 2.6.0

- Terraform version:
Terraform v1.9.3

- Provider version(s):
 provider registry.terraform.io/hashicorp/aws v5.53.0
provider registry.terraform.io/hashicorp/random v3.6.0

## Reproduction Code [Required]
1. State list 
<img width="597" alt="Screenshot 2024-08-28 at 18 27 36" src="https://github.com/user-attachments/assets/f5367d75-a2f3-47fc-b8a6-94dada65423a">

2. Importing resource aws_msk_configuration.this[0] command: 
**`terragrunt import 'aws_msk_configuration.this[0]' arn:aws:kafka:eu-west-3:xxxxxxxxxxxx:configuration/xxxxx-xxxxxx/xxxxxxxx-xxxx-4ddb-9f0f-5785e60adbd6-3`**
<img width="1592" alt="Screenshot 2024-08-28 at 18 32 01" src="https://github.com/user-attachments/assets/c12f2e06-a1f3-4feb-8d84-7b0ccedbccd8">
Import successful 

3. **`terragrunt plan`** comand output: 
<img width="1556" alt="edited" src="https://github.com/user-attachments/assets/15df8016-9cc0-44c4-b45b-2cef36036468">

Force replacement here (recreate of the resource).

4. Block of code for **`aws_msk_configuration`**:
<img width="760" alt="edited too" src="https://github.com/user-attachments/assets/6b6c9e00-38dd-4863-a5dd-f30df40f27e5">

**NAMES ARE IDENTICAL** (in code, and in aws)
Forces replacement here only for one reason - you added **`random_id`** resource at the end of  the configuration name
Here is **[permalink](https://github.com/terraform-aws-modules/terraform-aws-msk-kafka-cluster/blob/d5b6c958942ef06210571c329bc649646e4860cd/main.tf#L259)**
## Expected behavior
Adding the ability to omit the **`random_id`** resource from the end of the configuration name

## Actual behavior
Cannot correctly import resources to public module.

**Comment by bryantbiggs** [comment]
this was intended based on user feedback - without it, if you make a change to the configuration and try to apply it, it fails with a "this resource already exists" message. so the random part was added to allow folks to modify the configs and apply it. 

If you are importing, I would suggest letting Terraform replace the configs and you're now adopted into the module. If you want to modify this config in the future, you'll inevitably face this issue

**Comment by bryantbiggs** [comment]
see #17
